### ISSUE TITLE
few questions on the API

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/sdk-research#1]
looking at https://github.com/open-feature/sdk-research/blob/main/packages/openfeature-js/src/lib/types.ts, a few questions came up for me.

```
export type FlagEvaluationVariationResponse = FlagEvaluationResponse & {
  stringValue?: string;
  boolValue?: string;
  numberValue?: string;
};
```
I would have expected boolValue to be a bool, etc?

`FlagEvaluationRequest` should require a default, I believe, in the case of connectivity issues.

There's no way to understand why you got one of those results. e.g. did you match a rule? was it a fallthrough case? Useful for debugging.

Is there a use-case where folks don't know the data type their requesting? I would have guessed that:

```
  getVariation(
    id: string,
    context?: Context
  ): Promise<FlagEvaluationVariationResponse>
```

would actually return something like `Promise<FlagResponse<Boolean>>` instead.

I'm not clear why there's so much overlap on the data inside `getVariation` and `evaluateFlag`.

**Comment by beeme1mr** [comment]
@justinabrahms, good catch! Yes, I messed up the types on the FlagEvaluationVariationResponse. I'll fix that ASAP.

I think handling fallback scenarios should be part of a bigger discussion. In JavaScript, it would be nice to pass in an optional callback. One of the arguments could be an error type. The developer would have more context around the issue so they could handle it how they see fit.

For example:

```typescript
isEnabled("test-feature", { user: "test-user" }, (errType) => {
 console.log(errType)
 return false;
})
```

We could also accept a default value like this.

```typescript
isEnabled("test-feature", { user: "test-user" }, false);
```

**Comment by beeme1mr** [comment]
Perhaps it would be better to have methods that explicitly handle data types instead of having a single method. My thought around the single method is that additional data could be included in the response like a flag evaluation summary. What would be your preference?

**Comment by justinabrahms** [comment]
We'd primarily use it for logs/debugging purposes.

**Comment by toddbaert** [comment]
I think the current spec addresses most of these concerns. Please re-open if you disagree.
