### ISSUE TITLE
can we avoid API consumers having to provide a client name each time

### ISSUE THREAD

**Issue by moredip** [open-feature/sdk-research#2]
Currently wherever a consumer needs to evaluate a flag, they grab a client by doing something like 

`const oFeatClient = openfeature.getClient('fibonacci');`

Can we avoid them having to provide the client name (`'fibonacci'`) each time? Can it be specified during configuration/initialization instead?

**Comment by beeme1mr** [comment]
It's worth noting that you only need to do this to create a client, not during flag evaluation.

**Comment by moredip** [comment]
That's an interesting point @toddbaert. It does seem like that namespacing capability could be a nice flexible extension point to the API. I would still argue strongly that providing the name should be optional, to keep the simple case simple.

**Comment by beeme1mr** [comment]
This is now optional.
