### ISSUE TITLE
Hooks in the invocation?

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/sdk-research#24]
Why is there a param for Hook in the invocation (e.g. `getBooleanDetails`)? What's the use-case there?

**Comment by justinabrahms** [comment]
That didn't take long. We thought of one right around the time we were complaining about how it didn't make sense. ;)

We're thinking we might use it to override a global hook.

**Comment by beeme1mr** [comment]
Hey @justinabrahms, I think it just gives the app developer flexibility. For example, you may want to add logging to a single flag evaluation or validate a return value like we did [here](https://github.com/open-feature/community/pull/46).
