### ISSUE TITLE
in Context, `userId` might be a bit overly specific 

### ISSUE THREAD

**Issue by moredip** [open-feature/sdk-research#3]
In some controlled rollout scenarios, cohorting is done by something other than user. For example, if you're canary releasing a new caching layer you might choose to turn it on for a subset of servers. So calling the hash input `userId` might be a bit confusing. Not sure what a better name is thought 🙃

**Comment by toddbaert** [comment]
We have opened a spec issue for context: https://github.com/open-feature/spec/issues/43, I'll close this and we can move the discussion there.

**Comment by weyert** [comment]
I would suggest `distinctId` as in distinct identifier, for e.g. user, group, company etc
